// Locate and instantiate the Emscripten WASM engine as a Node ES module.
//
// The module (`mathsolver.js` + `mathsolver.wasm`) is generated by
// tools/build_wasm.sh and staged into apps/ink/wasm (and web/src/lib/wasm).
// It is a build artifact — never committed — so this loader searches a few
// well-known locations and fails with an actionable message when none holds a
// build yet.

import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { MathSolverModule } from "./module.js";

/** Thrown when no built engine can be found; carries user-facing guidance. */
export class EngineLoadError extends Error {
  constructor(
    message: string,
    readonly searched: string[],
  ) {
    super(message);
    this.name = "EngineLoadError";
  }
}

const here = dirname(fileURLToPath(import.meta.url));
// dist/engine/load.js (built) or src/engine/load.ts (tsx) → apps/ink
const packageRoot = resolve(here, "..", "..");
// apps/ink → repository root
const repoRoot = resolve(packageRoot, "..", "..");

/** Directories that may hold a built engine, in priority order. */
function candidateDirs(): string[] {
  const dirs: string[] = [];
  const override = process.env.MATHSOLVER_WASM_DIR;
  if (override) dirs.push(override);
  dirs.push(join(packageRoot, "wasm"));
  dirs.push(join(repoRoot, "build-wasm"));
  dirs.push(join(repoRoot, "web", "src", "lib", "wasm"));
  return dirs;
}

/** The first candidate directory that contains a complete build, or null. */
export function findEngineDir(): string | null {
  for (const dir of candidateDirs()) {
    if (existsSync(join(dir, "mathsolver.js")) && existsSync(join(dir, "mathsolver.wasm"))) {
      return dir;
    }
  }
  return null;
}

/**
 * Load the engine. Resolves to the raw WASM module; rejects with an
 * EngineLoadError (with build guidance) when no build is present.
 */
export async function loadEngineModule(): Promise<MathSolverModule> {
  const dir = findEngineDir();
  if (!dir) {
    const searched = candidateDirs();
    throw new EngineLoadError(
      "MathSolver WASM engine not found. Build it once with:\n" +
        "    bash tools/build_wasm.sh\n" +
        "(requires Emscripten: emcmake/emcc on PATH), or set MATHSOLVER_WASM_DIR\n" +
        "to a directory containing mathsolver.js + mathsolver.wasm.",
      searched,
    );
  }
  const jsUrl = pathToFileURL(join(dir, "mathsolver.js")).href;
  const mod = (await import(jsUrl)) as {
    default: (options?: { locateFile?: (path: string) => string }) => Promise<MathSolverModule>;
  };
  return mod.default({
    // Resolve the sidecar .wasm next to the .js regardless of cwd.
    locateFile: (path) => (path.endsWith(".wasm") ? join(dir, "mathsolver.wasm") : path),
  });
}
